### ISSUE TITLE
Endpoint Request: ALLOW_EXTEND_MATCH: 93

### ISSUE THREAD

**Issue by ramazansancar** [henrydatei/bumble-api#4]
Feature `ALLOW_EXTEND_MATCH:93` Is there an endpoint we can use?

When I examined the source code on Bumble.com, I saw that it was almost the same as badoo.com, and the only difference was the domain. Maybe [this repo](https://github.com/quark1482/badwrapi) can help with development.

Enum List:
https://github.com/quark1482/badwrapi/blob/main/src/badooenums.h

**Comment by henrydatei** [comment]
Thanks for your feature request. It would be highly appreciated, if you can send me the complete request and response when you access this endpoint. If you don't have the data - no problem, but do you know what functionality from Bumble is using this endpoint? From the name it sounds like that it is some type of setting, right? If yes, how do I find it?

**Comment by ramazansancar** [comment]
I haven't discovered Endpoint yet. I didn't review the source code but it was a bit difficult :/
This endpoint is used after the match to extend the right to send messages again, free of charge (once a day) or for a fee, after the message sending period expires.

All I could do was create a script for pre-request in Postman.

```js
function computeSignature(body) {
  const text = body + 'whitetelevisionbulbelectionroofhorseflying';
  return CryptoJS.MD5(text).toString();
}

pm.globals.set("bumblePingBack", computeSignature(pm.request.body.raw));
```

Usage:
Header,
```text
X-Pingback: {{bumblePingBack}}
```

**Comment by henrydatei** [comment]
Ok than I try to replicate this behavior, extend a match and see how I can implement this

**Comment by ramazansancar** [comment]
Thanks @henrydatei

**Comment by henrydatei** [comment]
That is the request that is send from the web client to bumble when I extend a match
```bash
curl 'https://fr1.bumble.com/mwebapi.phtml?SERVER_USER_ACTION' \
  -H 'Accept: */*' \
  -H 'Accept-Language: de-DE,de;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: session_cookie_name=session; device_id=***; first_web_visit_id=***; dnsDisplayed=undefined; ccpaApplies=false; signedLspa=undefined; _sp_su=false; ccpaUUID=***; consentUUID=***; consentDate=2024-05-22T19:46:13.299Z; _gcl_au=1.1.1664597860.1716407173; _pin_unauth=***; _fbp=fb.1.1716407174095.1864692518; _gid=GA1.2.1906655704.1716407196; buzz_lang_code=en-us; _ga=GA1.2.2104056499.1716407170; _ga_H6H4KZQ2YD=GS1.2.1716407196.1.1.1716407366.60.0.0; HDR-X-User-id=***; has_secure_session=1; aid=1851023999; wpr=1; session=***; cpc={%22c%22:0%2C%22e%22:1718999929356%2C%22u%22:%22zAhMACjE4NTEwMjM5OTkAINWHNfA5RrcB79MJbvliIcebyVHKZKbdpOv7cs2KkCx7%22}; _ga_NSEKRQF5TF=GS1.1.1716407169.1.1.1716408305.59.0.0' \
  -H 'Origin: https://bumble.com' \
  -H 'Pragma: no-cache' \
  -H 'Referer: https://bumble.com/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
  -H 'X-Message-type: 541' \
  -H 'X-Pingback: de27aea2cd45cf248afaa7b2dffb5e1d' \
  -H 'sec-ch-ua: "Not-A.Brand";v="99", "Chromium";v="124"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'x-use-session-cookie: 1' \
  --data-raw '{"$gpb":"badoo.bma.BadooMessage","body":[{"message_type":541,"server_user_action":{"action_type":2,"client_source":10,"user_id":"***"}}],"message_id":157,"message_type":541,"version":1,"is_background":false}'
```
this returns
```json
{
    "$gpb": "badoo.bma.BadooMessage",
    "message_type": 387,
    "version": 1,
    "message_id": 157,
    "body": [
        {
            "$gpb": "badoo.bma.MessageBody",
            "message_type": 387
        }
    ],
    "responses_count": 1,
    "is_background": false,
    "vhost": ""
}
```
But this doesn't look like it is using ALLOW_EXTEND_MATCH...

**Comment by ramazansancar** [comment]
Yes, as you said, this seems to take a different action. @henrydatei

**Comment by henrydatei** [comment]
I also did some other actions in bumble and searched through the requests but this ALLOW_EXTEND_MATCH never appeared. So I guess this might be something that is used only by the mobile app (I was using the web version of bumble), or in other modes of bumble like BFF and Networking or this is a very obscure action. 

The other question is: Why do you want this to be implemented? I can implement my found request for extending a match.

**Comment by ramazansancar** [comment]
I just want to see how far you can go. I use it for security research. @henrydatei

**Comment by henrydatei** [comment]
Ok then I'll close the issue
